name: "selftesting"
on:
  issue:
    types: [opened]

jobs:
  antispam:
    name: AntiSpam
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
