name: "selftesting"
on:
  issues:
    types: opened
jobs:
  antispam:
    name: AntiSpam
    runs-on: ubuntu-latest
    steps:
      - uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
