name: "selftesting"
on:
  issue_comment:
    types: created

jobs:
  bisects:
    if: |
      github.event_name == 'issue_comment' && github.event.issue.pull_request == null
    name: AntiSpam
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
