name: "selftesting"
on:
  issues:
    types: opened

jobs:
  antispam:
    name: AntiSpam
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
